# Generated by Django 5.2.5 on 2025-10-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogory',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
